In [1]:
import numpy as np

In [161]:
X = np.array([ [1,1,0],[0,0,0],[0,0,1],[0,1,1],[1,0,1],[1,1,1],[1,1,1] ])
y = np.array([[1,0,0,1,1,0,0]]).T

In [135]:
X.shape

(7, 3)

In [136]:
y.shape

(7, 1)

In [286]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

def train(X,y,size=3):
    err = []
    syn0 = 2*np.random.random((X.shape[1],size)) - 1
    syn1 = 2*np.random.random((size,y.shape[1])) - 1
    for j in range(60000):
        l1 = sigmoid(np.dot(X,syn0))
        l2 = sigmoid(np.dot(l1,syn1))
        l2_delta = (y - l2)*(l2*(1-l2))
        err.append(l2_delta)
        if (j % 1000) == 0:
            print(np.mean(err).round(6))
            err = []
        l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
        syn1 += l1.T.dot(l2_delta)
        syn0 += X.T.dot(l1_delta)
    return syn0,syn1
syn0,syn1 = train(X,y)

-0.010567
-0.004935
0.007801
0.017497
0.017499
0.017499
0.017499
0.017499
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175
0.0175


In [287]:
X2 = np.array([[0,0,0], [0,0,1],[0,1,0],[1,0,0],[1,1,0],[1,0,1],[0,1,1],[1,1,1] ])

In [288]:
l1 = sigmoid(np.dot(X2,syn0))
l2 = sigmoid(np.dot(l1,syn1))

In [291]:
l2.round(3)

array([[0.001],
       [0.   ],
       [0.002],
       [0.002],
       [0.999],
       [0.5  ],
       [0.999],
       [0.001]])

In [292]:
X = []
y = []
for _ in range(100):
    x1=[]
    for x in range(3):
        x1.append(np.random.binomial(1,.6))
    X.append(x1)
    if np.sum(x1) ==2:
        y.append(1)
    else:
        y.append(0)
X = np.array(X)
y = np.array([y]).T

In [293]:
syn0,syn1 = train(X,y)

0.031581
0.036631
0.037494
0.037497
0.037498
0.037499
0.037499
0.037499
0.037499
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375
0.0375


In [294]:
X.shape

(100, 3)

In [295]:
y.shape

(100, 1)

In [296]:
l1 = 1/(1+np.exp(-(np.dot(X2,syn0))))
l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
l2.round(2)

array([[0. ],
       [0. ],
       [0. ],
       [0. ],
       [0.5],
       [0.5],
       [0.5],
       [0.5]])

In [279]:
X2

array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [1, 1, 0],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 1]])

In [230]:
X

array([[1, 1, 0],
       [1, 0, 0],
       [0, 0, 0],
       ...,
       [1, 1, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [231]:
y

array([[1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
    